#!/bin/sh

set -e

aardir=$(dirname $(readlink -f $0))
tools=$(sh "$aardir/aardvark.test")
ACC=$(echo "$tools" | awk -F '|' '{print $1}')
AOC=$(echo "$tools" | awk -F '|' '{print $2}')
AD=$(echo "$tools" | awk -F '|' '{print $3}')

help() {
  echo 'Help - Aardvark v0.0'
  echo '===================='
  echo ''
  echo 'aardvark listmodel | Show supported devices.'
  echo 'aardvark --help | Show this message.'
  exit 0
}

#Error codes
INVALIDMODEL=100

if [ -z "$1" ]; then
  help
fi

if [ "$1" = "--help" ]; then
  help
fi

if [ "$1" = 'listmodel' ]; then
  cat "$aardir/aardvark.models" | awk -F '|' '{print $1}'
  exit 0
fi

echo "Using compiler: $ACC"
echo "Using objcopy: $AOC"
echo "Using uploader: $AD"

# check if matches line in .models
if grep -q "$1 |" "$aardir/aardvark.models"; then
  MODEL="$1"
fi

if [ -z "$MODEL" ]; then
  echo 'Model is not supported. (Check [aardvark listmodel])' 1>&2
  exit $INVALIDMODEL
fi
